import sqlite3

def get_db_connection():
    conn = sqlite3.connect('nutriplan.db')
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db_connection()
    c = conn.cursor()

    c.execute('''
        CREATE TABLE IF NOT EXISTS recipes (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            calories INTEGER NOT NULL,
            protein REAL NOT NULL,
            carbs REAL NOT NULL,
            fat REAL NOT NULL,
            cost INTEGER NOT NULL,
            tags TEXT NOT NULL,
            allergens TEXT,
            ingredients TEXT
        )
    ''')

    recipes = [
        # ───────────── BREAKFASTS (1-75) ─────────────
        (1,  'Oats Upma',            'breakfast', 300, 8,  45, 8,  40,  'veg,vegan,gf',             '',       'oats,vegetables,mustard'),
        (2,  'Egg Bhurji',           'breakfast', 280, 18, 5,  20, 50,  'non-veg,keto,high-protein','',       'eggs,onion,spices'),
        (3,  'Poha',                 'breakfast', 250, 6,  40, 5,  35,  'veg,vegan',                '',       'poha,peanuts,lemon'),
        (4,  'Idli Sambar',          'breakfast', 200, 6,  35, 2,  30,  'veg,vegan,gf',             '',       'rice,lentils,spices'),
        (5,  'Aloo Paratha',         'breakfast', 400, 8,  60, 15, 45,  'veg',                      'gluten', 'wheat,potato,spices'),
        (6,  'Besan Chilla',         'breakfast', 280, 12, 30, 10, 40,  'veg,gf',                   '',       'besan,vegetables,spices'),
        (7,  'Methi Thepla',         'breakfast', 320, 9,  45, 10, 35,  'veg',                      'gluten', 'wheat,fenugreek,spices'),
        (8,  'Ragi Dosa',            'breakfast', 220, 6,  40, 4,  35,  'veg,vegan,gf',             '',       'ragi,urad-dal,spices'),
        (9,  'Moong Dal Cheela',     'breakfast', 250, 14, 30, 8,  40,  'veg,vegan,gf',             '',       'moong-dal,spices'),
        (10, 'Upma',                 'breakfast', 290, 7,  42, 9,  38,  'veg,vegan',                '',       'semolina,vegetables,mustard'),
        (11, 'Banana Oats Smoothie', 'breakfast', 350, 12, 50, 8,  60,  'veg,gf',                   'dairy',  'banana,oats,milk'),
        (12, 'Masala Omelette',      'breakfast', 320, 22, 5,  24, 55,  'non-veg,keto,high-protein','',       'eggs,onion,tomato,spices'),
        (13, 'Dosa Chutney',         'breakfast', 280, 7,  45, 6,  40,  'veg,vegan,gf',             '',       'rice,urad-dal,coconut'),
        (14, 'Pesarattu',            'breakfast', 280, 16, 38, 6,  40,  'veg,vegan,gf,high-protein','',       'moong-dal,ginger,spices'),
        (15, 'Bread Omelette',       'breakfast', 380, 22, 30, 16, 55,  'non-veg,high-protein',     'gluten', 'bread,eggs,butter'),
        (16, 'Dhokla',               'breakfast', 240, 10, 32, 6,  40,  'veg,gf',                   '',       'besan,yogurt,spices'),
        (17, 'Pongal',               'breakfast', 320, 10, 48, 9,  40,  'veg,gf',                   '',       'rice,moong-dal,ghee'),
        (18, 'Vermicelli Upma',      'breakfast', 320, 8,  50, 8,  45,  'veg,vegan',                'gluten', 'vermicelli,vegetables,mustard'),
        (19, 'Sabudana Khichdi',     'breakfast', 380, 6,  62, 10, 50,  'veg,vegan,gf',             '',       'sabudana,peanuts,potato'),
        (20, 'Rava Idli',            'breakfast', 270, 8,  42, 6,  40,  'veg',                      '',       'semolina,yogurt,spices'),
        (21, 'Paneer Paratha',       'breakfast', 450, 20, 55, 18, 70,  'veg,high-protein',         'gluten,dairy', 'wheat,paneer,spices'),
        (22, 'Corn Flakes Milk',     'breakfast', 320, 12, 55, 6,  60,  'veg',                      'dairy',  'cornflakes,milk,sugar'),
        (23, 'Stuffed Capsicum',     'breakfast', 300, 14, 30, 12, 70,  'veg,gf,high-protein',      'dairy',  'capsicum,paneer,spices'),
        (24, 'Boiled Eggs Toast',    'breakfast', 380, 24, 30, 14, 55,  'non-veg,high-protein',     'gluten', 'eggs,bread,butter'),
        (25, 'Sprouts Chaat',        'breakfast', 240, 16, 30, 4,  40,  'veg,vegan,gf,high-protein','',       'sprouts,onion,lemon,spices'),
        (26, 'Wheat Dalia',          'breakfast', 280, 9,  44, 5,  35,  'veg,vegan',                'gluten', 'dalia,vegetables,spices'),
        (27, 'Egg Sandwich',         'breakfast', 400, 22, 38, 16, 60,  'non-veg,high-protein',     'gluten,dairy', 'bread,eggs,cheese,vegetables'),
        (28, 'Coconut Chutney Dosa', 'breakfast', 280, 7,  44, 7,  42,  'veg,vegan,gf',             '',       'rice,urad-dal,coconut'),
        (29, 'Millet Porridge',      'breakfast', 280, 9,  44, 6,  38,  'veg,vegan,gf',             '',       'millet,water,jaggery'),
        (30, 'Greek Yogurt Bowl',    'breakfast', 320, 22, 30, 8,  80,  'veg,high-protein',         'dairy',  'yogurt,fruits,honey'),
        (31, 'Quinoa Upma',          'breakfast', 340, 14, 44, 10, 90,  'veg,vegan,gf,high-protein','',       'quinoa,vegetables,spices'),
        (32, 'Akki Roti',            'breakfast', 290, 6,  46, 7,  40,  'veg,vegan,gf',             '',       'rice-flour,vegetables,spices'),
        (33, 'Thepla Curd',          'breakfast', 380, 12, 48, 14, 50,  'veg',                      'gluten,dairy', 'wheat,fenugreek,yogurt'),
        (34, 'Banana Pancake',       'breakfast', 350, 12, 50, 10, 55,  'veg',                      'gluten,dairy', 'banana,flour,eggs,milk'),
        (35, 'Egg Paratha',          'breakfast', 440, 22, 45, 18, 65,  'non-veg,high-protein',     'gluten', 'wheat,eggs,onion'),
        (36, 'Paneer Bhurji Toast',  'breakfast', 420, 24, 32, 22, 80,  'veg,high-protein',         'gluten,dairy', 'paneer,bread,onion'),
        (37, 'Misal Pav',            'breakfast', 480, 18, 55, 18, 60,  'veg,high-protein',         'gluten', 'sprouts,bread,spices'),
        (38, 'Chicken Sausage Eggs', 'breakfast', 460, 32, 8,  30, 130, 'non-veg,high-protein,keto','',       'chicken-sausage,eggs,butter'),
        (39, 'Tofu Scramble',        'breakfast', 300, 22, 12, 18, 80,  'veg,vegan,gf,high-protein','soy',    'tofu,vegetables,spices'),
        (40, 'Anda Bhurji Pav',      'breakfast', 420, 22, 38, 18, 60,  'non-veg,high-protein',     'gluten', 'eggs,bread,onion,spices'),
        (41, 'Idli Podi',            'breakfast', 260, 8,  40, 6,  35,  'veg,vegan,gf',             '',       'rice,urad-dal,podi'),
        (42, 'Ragi Mudde',           'breakfast', 280, 8,  46, 4,  35,  'veg,vegan,gf',             '',       'ragi,water'),
        (43, 'Veg Sandwich',         'breakfast', 320, 10, 40, 12, 50,  'veg',                      'gluten,dairy', 'bread,vegetables,cheese'),
        (44, 'Aloo Tikki',           'breakfast', 320, 6,  44, 12, 40,  'veg,vegan',                '',       'potato,spices'),
        (45, 'Sheera',               'breakfast', 380, 8,  55, 14, 50,  'veg',                      'gluten,dairy', 'semolina,ghee,sugar'),
        (46, 'Rava Dosa',            'breakfast', 290, 7,  45, 8,  40,  'veg,vegan',                '',       'semolina,rice-flour,spices'),
        (47, 'Uttapam',              'breakfast', 320, 9,  48, 8,  45,  'veg,vegan,gf',             '',       'rice,urad-dal,vegetables'),
        (48, 'Egg Curry Roti',       'breakfast', 460, 26, 38, 20, 75,  'non-veg,high-protein',     'gluten', 'eggs,wheat,spices'),
        (49, 'Soya Bhurji',          'breakfast', 320, 22, 18, 14, 60,  'veg,high-protein',         'soy',    'soya,onion,spices'),
        (50, 'Mango Lassi Bowl',     'breakfast', 340, 14, 48, 8,  70,  'veg',                      'dairy',  'mango,yogurt,oats'),
        (51, 'Cheese Omelette',      'breakfast', 380, 26, 4,  28, 80,  'non-veg,keto,high-protein','dairy',  'eggs,cheese,butter'),
        (52, 'Avocado Toast',        'breakfast', 360, 12, 38, 18, 100, 'veg,vegan',                'gluten', 'bread,avocado,seeds'),
        (53, 'Chana Chaat',          'breakfast', 280, 14, 36, 6,  40,  'veg,vegan,gf,high-protein','',       'chickpeas,onion,lemon'),
        (54, 'Paneer Roll',          'breakfast', 420, 22, 38, 18, 75,  'veg,high-protein',         'gluten,dairy', 'paneer,wheat,spices'),
        (55, 'Veg Frankie',          'breakfast', 380, 10, 50, 14, 60,  'veg',                      'gluten', 'wheat,vegetables,spices'),
        (56, 'Chicken Roll',         'breakfast', 460, 28, 40, 18, 100, 'non-veg,high-protein',     'gluten', 'chicken,wheat,vegetables'),
        (57, 'Smoothie Bowl',        'breakfast', 360, 10, 56, 10, 90,  'veg,gf',                   'dairy,nuts', 'fruits,yogurt,nuts'),
        (58, 'Tofu Paratha',         'breakfast', 420, 20, 48, 16, 75,  'veg,vegan,high-protein',   'gluten,soy', 'wheat,tofu,spices'),
        (59, 'Methi Khakra',         'breakfast', 220, 6,  38, 5,  30,  'veg,vegan',                'gluten', 'wheat,fenugreek,spices'),
        (60, 'Boiled Egg White (4)', 'breakfast', 140, 28, 2,  0,  40,  'non-veg,keto,high-protein,low-carb','','egg-whites,salt'),
        (61, 'Quinoa Porridge',      'breakfast', 320, 12, 44, 8,  90,  'veg,vegan,gf,high-protein','',       'quinoa,milk,fruits'),
        (62, 'Chicken Keema Toast',  'breakfast', 480, 30, 32, 22, 110, 'non-veg,high-protein',     'gluten', 'chicken,bread,spices'),
        (63, 'Paneer Kathi Roll',    'breakfast', 460, 24, 42, 20, 80,  'veg,high-protein',         'gluten,dairy', 'paneer,wheat,vegetables'),
        (64, 'Spinach Omelette',     'breakfast', 320, 24, 6,  22, 60,  'non-veg,keto,high-protein','',       'eggs,spinach,onion'),
        (65, 'Soya Cutlet',          'breakfast', 320, 22, 28, 12, 65,  'veg,high-protein',         'soy',    'soya,potato,spices'),
        (66, 'Suji Chilla',          'breakfast', 280, 8,  44, 6,  35,  'veg',                      '',       'semolina,vegetables,spices'),
        (67, 'Chickpea Pancake',     'breakfast', 300, 14, 32, 10, 45,  'veg,vegan,gf,high-protein','',       'besan,vegetables,spices'),
        (68, 'Egg Wrap',             'breakfast', 420, 24, 36, 18, 70,  'non-veg,high-protein',     'gluten', 'eggs,wheat,vegetables'),
        (69, 'Oats Cheela',          'breakfast', 280, 12, 38, 6,  40,  'veg,gf',                   '',       'oats,vegetables,spices'),
        (70, 'Paneer Toast',         'breakfast', 380, 22, 30, 18, 75,  'veg,high-protein',         'gluten,dairy', 'bread,paneer,spices'),
        (71, 'Veg Cheela',           'breakfast', 240, 10, 30, 6,  35,  'veg,vegan,gf',             '',       'besan,vegetables'),
        (72, 'Egg White Omelette',   'breakfast', 200, 24, 4,  10, 50,  'non-veg,keto,high-protein,low-carb','','egg-whites,vegetables'),
        (73, 'Methi Paratha',        'breakfast', 360, 10, 50, 14, 45,  'veg',                      'gluten', 'wheat,fenugreek,spices'),
        (74, 'Sambar Vada',          'breakfast', 380, 12, 50, 14, 50,  'veg,vegan',                '',       'urad-dal,lentils,spices'),
        (75, 'Tofu Bhurji Toast',    'breakfast', 380, 22, 32, 16, 80,  'veg,vegan,high-protein',   'gluten,soy', 'tofu,bread,onion'),

        # ───────────── LUNCHES (76-160) ─────────────
        (76,  'Rajma Chawal',         'lunch', 600, 22, 80, 14, 70,  'veg,high-protein',     '',           'rajma,rice,onion,tomato'),
        (77,  'Grilled Chicken Bowl', 'lunch', 550, 45, 30, 20, 140, 'non-veg,high-protein,low-carb','',   'chicken,quinoa,vegetables'),
        (78,  'Dal Tadka Rice',       'lunch', 520, 18, 70, 12, 55,  'veg,vegan,gf,high-protein','',       'lentils,rice,ghee'),
        (79,  'Paneer Butter Masala', 'lunch', 620, 26, 30, 38, 110, 'veg,high-protein',     'dairy',      'paneer,cream,tomato,rice'),
        (80,  'Chole Bhature',        'lunch', 650, 18, 80, 22, 90,  'veg',                  'gluten',     'chickpea,flour,spices'),
        (81,  'Fish Curry Rice',      'lunch', 580, 38, 60, 18, 140, 'non-veg,high-protein', '',           'fish,coconut,rice'),
        (82,  'Mushroom Matar Pulao', 'lunch', 480, 14, 70, 12, 80,  'veg,vegan,gf',         '',           'mushroom,peas,rice'),
        (83,  'Egg Curry Rice',       'lunch', 580, 28, 65, 22, 90,  'non-veg,high-protein', '',           'eggs,tomato,rice'),
        (84,  'Chicken Biryani',      'lunch', 700, 35, 80, 24, 160, 'non-veg,high-protein', '',           'rice,chicken,spices'),
        (85,  'Vegetable Pulao',      'lunch', 480, 12, 70, 12, 65,  'veg,vegan',            '',           'rice,mixed-veg,spices'),
        (86,  'Mutton Curry Rice',    'lunch', 700, 38, 60, 32, 200, 'non-veg,high-protein', '',           'mutton,onion,rice'),
        (87,  'Aloo Gobi Roti',       'lunch', 480, 12, 65, 14, 60,  'veg,vegan',            'gluten',     'potato,cauliflower,wheat'),
        (88,  'Kadai Paneer Roti',    'lunch', 620, 26, 50, 32, 130, 'veg,high-protein',     'gluten,dairy','paneer,capsicum,wheat'),
        (89,  'Chicken Fried Rice',   'lunch', 620, 32, 70, 20, 130, 'non-veg,high-protein', '',           'rice,chicken,eggs'),
        (90,  'Sambar Rice',          'lunch', 480, 14, 70, 10, 55,  'veg,vegan,gf',         '',           'rice,lentils,vegetables'),
        (91,  'Prawn Curry Rice',     'lunch', 580, 32, 60, 22, 170, 'non-veg,high-protein', '',           'prawns,coconut,rice'),
        (92,  'Chana Masala Rice',    'lunch', 540, 20, 75, 12, 65,  'veg,vegan,gf,high-protein','',       'chickpea,rice,spices'),
        (93,  'Egg Fried Rice',       'lunch', 560, 24, 70, 18, 100, 'non-veg,high-protein', '',           'rice,eggs,vegetables'),
        (94,  'Palak Dal Rice',       'lunch', 480, 20, 60, 12, 60,  'veg,vegan,gf,high-protein','',       'spinach,lentils,rice'),
        (95,  'Keema Matar Roti',     'lunch', 620, 36, 50, 28, 150, 'non-veg,high-protein', 'gluten',     'minced-meat,peas,wheat'),
        (96,  'Veg Biryani',          'lunch', 560, 14, 80, 16, 90,  'veg,vegan',            '',           'rice,mixed-veg,spices'),
        (97,  'Toor Dal Rice',        'lunch', 460, 18, 65, 8,  50,  'veg,vegan,gf,high-protein','',       'toor-dal,rice,tomato'),
        (98,  'Chicken Curry Roti',   'lunch', 580, 38, 50, 22, 140, 'non-veg,high-protein', 'gluten',     'chicken,wheat,onion'),
        (99,  'Matar Paneer Rice',    'lunch', 580, 26, 60, 26, 110, 'veg,high-protein',     'dairy',      'paneer,peas,rice'),
        (100, 'Lemon Rice',           'lunch', 440, 9,  70, 10, 50,  'veg,vegan,gf',         '',           'rice,lemon,peanuts'),
        (101, 'Fish Fry Rice',        'lunch', 560, 34, 50, 24, 150, 'non-veg,high-protein', '',           'fish,rice,spices'),
        (102, 'Soya Chunks Curry',    'lunch', 480, 32, 40, 14, 70,  'veg,high-protein',     'soy',        'soya,onion,tomato'),
        (103, 'Aloo Matar Rice',      'lunch', 460, 12, 65, 12, 55,  'veg,vegan,gf',         '',           'potato,peas,rice'),
        (104, 'Chicken Kathi Roll',   'lunch', 560, 32, 55, 20, 130, 'non-veg,high-protein', 'gluten',     'wheat,chicken,vegetables'),
        (105, 'Urad Dal Rice',        'lunch', 460, 20, 60, 8,  55,  'veg,vegan,gf,high-protein','',       'urad-dal,rice'),
        (106, 'Paneer Bhurji Roti',   'lunch', 560, 28, 45, 28, 100, 'veg,high-protein',     'gluten,dairy','paneer,wheat,onion'),
        (107, 'Masala Fish Rice',     'lunch', 540, 32, 55, 22, 155, 'non-veg,high-protein', '',           'fish,rice,spices'),
        (108, 'Mixed Veg Rice',       'lunch', 440, 10, 60, 12, 60,  'veg,vegan,gf',         '',           'mixed-veg,rice'),
        (109, 'Tandoori Chicken',     'lunch', 480, 48, 8,  20, 150, 'non-veg,high-protein,low-carb','',   'chicken,yogurt,spices'),
        (110, 'Paneer Tikka Rice',    'lunch', 580, 28, 50, 26, 110, 'veg,high-protein',     'dairy',      'paneer,yogurt,rice'),
        (111, 'Egg Biryani',          'lunch', 580, 24, 70, 18, 100, 'non-veg,high-protein', '',           'rice,eggs,spices'),
        (112, 'Paneer Curry Rice',    'lunch', 580, 26, 55, 26, 105, 'veg,high-protein',     'dairy',      'paneer,rice,onion'),
        (113, 'Mutton Biryani',       'lunch', 720, 38, 80, 28, 200, 'non-veg,high-protein', '',           'mutton,rice,spices'),
        (114, 'Tofu Stir Fry',        'lunch', 460, 28, 30, 22, 100, 'veg,vegan,high-protein','soy',       'tofu,vegetables,soy'),
        (115, 'Veg Manchurian',       'lunch', 480, 12, 60, 18, 80,  'veg,vegan',            'gluten,soy', 'vegetables,flour,sauce'),
        (116, 'Chicken Manchurian',   'lunch', 580, 32, 50, 22, 140, 'non-veg,high-protein', 'gluten,soy', 'chicken,vegetables,sauce'),
        (117, 'Veg Thali',            'lunch', 600, 18, 80, 18, 100, 'veg',                  'gluten,dairy','roti,sabzi,dal,rice'),
        (118, 'Non-veg Thali',        'lunch', 700, 35, 70, 26, 150, 'non-veg,high-protein', 'gluten',     'chicken,roti,dal,rice'),
        (119, 'Lemon Chicken',        'lunch', 480, 38, 20, 22, 130, 'non-veg,high-protein', '',           'chicken,lemon,spices'),
        (120, 'Pesto Pasta',          'lunch', 580, 18, 70, 22, 110, 'veg',                  'gluten,nuts,dairy','pasta,basil,nuts'),
        (121, 'Chicken Pasta',        'lunch', 620, 38, 65, 22, 140, 'non-veg,high-protein', 'gluten,dairy','pasta,chicken,sauce'),
        (122, 'Methi Chicken',        'lunch', 480, 36, 18, 22, 130, 'non-veg,high-protein', '',           'chicken,fenugreek,spices'),
        (123, 'Bhindi Masala Roti',   'lunch', 460, 12, 60, 14, 60,  'veg,vegan',            'gluten',     'okra,wheat,spices'),
        (124, 'Dum Aloo Rice',        'lunch', 540, 12, 70, 18, 70,  'veg',                  'dairy',      'potato,yogurt,rice'),
        (125, 'Veg Korma Rice',       'lunch', 580, 14, 70, 22, 90,  'veg',                  'dairy,nuts', 'mixed-veg,cream,nuts'),
        (126, 'Chicken Korma Rice',   'lunch', 640, 36, 65, 26, 140, 'non-veg,high-protein', 'dairy,nuts', 'chicken,cream,rice'),
        (127, 'Curd Rice Pickle',     'lunch', 440, 14, 65, 10, 50,  'veg',                  'dairy',      'rice,yogurt,pickle'),
        (128, 'Bisi Bele Bath',       'lunch', 520, 18, 70, 14, 60,  'veg,vegan,high-protein','',          'rice,lentils,vegetables'),
        (129, 'Pulav with Raita',     'lunch', 540, 16, 70, 16, 70,  'veg',                  'dairy',      'rice,vegetables,yogurt'),
        (130, 'Rajasthani Thali',     'lunch', 660, 22, 75, 24, 110, 'veg,high-protein',     'gluten,dairy','dal,bati,churma'),
        (131, 'Avial Rice',           'lunch', 480, 12, 65, 14, 70,  'veg,vegan,gf',         '',           'mixed-veg,coconut,rice'),
        (132, 'Egg Masala Roti',      'lunch', 540, 28, 50, 22, 90,  'non-veg,high-protein', 'gluten',     'eggs,wheat,onion'),
        (133, 'Methi Aloo Roti',      'lunch', 480, 12, 60, 18, 60,  'veg,vegan',            'gluten',     'fenugreek,potato,wheat'),
        (134, 'Tawa Veg Roti',        'lunch', 460, 12, 58, 14, 65,  'veg,vegan',            'gluten',     'mixed-veg,wheat,spices'),
        (135, 'Moong Dal Khichdi',    'lunch', 460, 18, 65, 10, 55,  'veg,vegan,gf,high-protein','',       'moong-dal,rice,spices'),
        (136, 'Coconut Rice',         'lunch', 460, 8,  65, 14, 50,  'veg,vegan,gf',         '',           'rice,coconut,spices'),
        (137, 'Paneer Korma',         'lunch', 620, 26, 45, 32, 110, 'veg,high-protein',     'dairy,nuts', 'paneer,cream,rice'),
        (138, 'Chicken Tikka Masala', 'lunch', 620, 38, 45, 28, 140, 'non-veg,high-protein', 'dairy',      'chicken,cream,rice'),
        (139, 'Veg Hyderabadi Biryani','lunch',560, 14, 80, 16, 90,  'veg',                  '',           'rice,vegetables,spices'),
        (140, 'Mushroom Pulao',       'lunch', 480, 14, 65, 14, 75,  'veg,vegan,gf',         '',           'mushroom,rice,spices'),
        (141, 'Chettinad Chicken',    'lunch', 560, 38, 30, 26, 140, 'non-veg,high-protein', '',           'chicken,coconut,spices'),
        (142, 'Andhra Fish Curry',    'lunch', 560, 34, 40, 24, 150, 'non-veg,high-protein', '',           'fish,tamarind,spices'),
        (143, 'Dal Makhani Roti',     'lunch', 580, 22, 60, 24, 90,  'veg,high-protein',     'gluten,dairy','urad-dal,wheat,cream'),
        (144, 'Paneer Lababdar Rice', 'lunch', 620, 28, 55, 30, 120, 'veg,high-protein',     'dairy',      'paneer,cream,rice'),
        (145, 'Veg Stir Fry Rice',    'lunch', 460, 14, 60, 14, 65,  'veg,vegan',            'soy',        'vegetables,rice,sauce'),
        (146, 'Chicken Stir Fry',     'lunch', 540, 36, 40, 22, 130, 'non-veg,high-protein', 'soy',        'chicken,vegetables,sauce'),
        (147, 'Salmon Bowl',          'lunch', 580, 42, 40, 22, 220, 'non-veg,high-protein,low-carb','',   'salmon,quinoa,vegetables'),
        (148, 'Buddha Bowl',          'lunch', 480, 22, 50, 18, 100, 'veg,vegan,gf,high-protein','',       'quinoa,chickpea,vegetables'),
        (149, 'Tofu Curry Rice',      'lunch', 480, 26, 50, 18, 100, 'veg,vegan,high-protein','soy',       'tofu,rice,curry'),
        (150, 'Kofta Curry Rice',     'lunch', 580, 22, 55, 28, 110, 'veg,high-protein',     'dairy,nuts', 'paneer,cream,rice'),
        (151, 'Grilled Veg Sandwich', 'lunch', 420, 12, 50, 16, 70,  'veg',                  'gluten,dairy','bread,vegetables,cheese'),
        (152, 'Grilled Chicken Wrap', 'lunch', 520, 32, 45, 20, 130, 'non-veg,high-protein', 'gluten',     'chicken,wheat,vegetables'),
        (153, 'Saag Paneer',          'lunch', 540, 24, 30, 32, 100, 'veg,high-protein',     'dairy',      'spinach,paneer,cream'),
        (154, 'Saag Chicken',         'lunch', 540, 38, 25, 28, 140, 'non-veg,high-protein', 'dairy',      'spinach,chicken,cream'),
        (155, 'Lobia Curry Rice',     'lunch', 520, 22, 70, 12, 65,  'veg,vegan,gf,high-protein','',       'black-eyed-peas,rice'),
        (156, 'Kala Chana Rice',      'lunch', 520, 22, 65, 12, 60,  'veg,vegan,gf,high-protein','',       'black-chickpea,rice'),
        (157, 'Chicken Schezwan Rice','lunch', 600, 32, 65, 22, 140, 'non-veg,high-protein', 'soy',        'chicken,rice,sauce'),
        (158, 'Veg Schezwan Rice',    'lunch', 500, 12, 65, 18, 80,  'veg,vegan',            'soy',        'vegetables,rice,sauce'),
        (159, 'Khow Suey',            'lunch', 580, 26, 60, 24, 110, 'veg,high-protein',     'gluten,dairy','noodles,coconut,vegetables'),
        (160, 'Chicken Khow Suey',    'lunch', 620, 36, 55, 26, 140, 'non-veg,high-protein', 'gluten',     'chicken,noodles,coconut'),

        # ───────────── DINNERS (161-240) ─────────────
        (161, 'Paneer Tikka Roti',    'dinner', 540, 28, 40, 26, 110, 'veg,high-protein',     'gluten,dairy','paneer,wheat,spices'),
        (162, 'Dal Khichdi',          'dinner', 480, 18, 65, 12, 60,  'veg,vegan,gf,high-protein','',      'rice,lentils,ghee'),
        (163, 'Tandoori Roti Sabzi',  'dinner', 460, 14, 60, 14, 70,  'veg,vegan',            'gluten',    'wheat,mixed-veg'),
        (164, 'Chicken Soup Bowl',    'dinner', 380, 36, 18, 14, 120, 'non-veg,high-protein,low-carb','',  'chicken,broth,vegetables'),
        (165, 'Sprouts Salad Bowl',   'dinner', 320, 22, 38, 6,  60,  'veg,vegan,gf,high-protein','',      'sprouts,onion,vegetables'),
        (166, 'Palak Paneer Roti',    'dinner', 540, 26, 40, 26, 110, 'veg,high-protein',     'gluten,dairy','spinach,paneer,wheat'),
        (167, 'Soya Chaap Curry',     'dinner', 480, 28, 32, 18, 90,  'veg,high-protein',     'soy',       'soya,spices,cream'),
        (168, 'Veg Hakka Noodles',    'dinner', 480, 14, 70, 14, 80,  'veg,vegan',            'gluten,soy','noodles,vegetables,soy'),
        (169, 'Butter Chicken Roti',  'dinner', 620, 36, 40, 36, 150, 'non-veg,high-protein', 'gluten,dairy','chicken,butter,wheat'),
        (170, 'Baingan Bharta Roti',  'dinner', 380, 12, 45, 16, 70,  'veg,vegan',            'gluten',    'eggplant,wheat,onion'),
        (171, 'Grilled Fish Bowl',    'dinner', 440, 38, 20, 20, 150, 'non-veg,high-protein,low-carb','',  'fish,quinoa,vegetables'),
        (172, 'Methi Dal Rice',       'dinner', 460, 20, 60, 10, 55,  'veg,vegan,gf,high-protein','',      'lentils,fenugreek,rice'),
        (173, 'Chicken Tikka Roti',   'dinner', 520, 38, 35, 22, 140, 'non-veg,high-protein', 'gluten',    'chicken,wheat,yogurt'),
        (174, 'Veg Khichdi',          'dinner', 460, 14, 65, 10, 55,  'veg,vegan,gf',         '',          'rice,lentils,vegetables'),
        (175, 'Egg Bhurji Roti',      'dinner', 520, 26, 45, 22, 75,  'non-veg,high-protein', 'gluten',    'eggs,wheat,onion'),
        (176, 'Paneer Lababdar',      'dinner', 540, 26, 30, 32, 110, 'veg,high-protein',     'dairy',     'paneer,cream,tomato'),
        (177, 'Moong Dal Soup',       'dinner', 320, 18, 38, 6,  50,  'veg,vegan,gf,high-protein','',      'moong-dal,spices,lemon'),
        (178, 'Fish Tikka',           'dinner', 420, 36, 14, 22, 145, 'non-veg,high-protein', '',          'fish,yogurt,spices'),
        (179, 'Aloo Palak Roti',      'dinner', 460, 14, 55, 16, 65,  'veg,vegan',            'gluten',    'potato,spinach,wheat'),
        (180, 'Chicken Stew Rice',    'dinner', 460, 32, 40, 18, 130, 'non-veg,high-protein', '',          'chicken,vegetables,rice'),
        (181, 'Rajma Soup Bread',     'dinner', 420, 22, 50, 10, 60,  'veg,vegan,high-protein','gluten',   'rajma,bread,spices'),
        (182, 'Paneer Bhurji Roti',   'dinner', 520, 26, 45, 22, 95,  'veg,high-protein',     'gluten,dairy','paneer,wheat,onion'),
        (183, 'Masala Omelette Roti', 'dinner', 460, 26, 38, 18, 75,  'non-veg,high-protein', 'gluten',    'eggs,wheat,spices'),
        (184, 'Lauki Dal Rice',       'dinner', 420, 16, 55, 8,  50,  'veg,vegan,gf,high-protein','',      'bottle-gourd,lentils,rice'),
        (185, 'Chicken Salad Bowl',   'dinner', 380, 38, 16, 16, 130, 'non-veg,high-protein,low-carb','',  'chicken,lettuce,vegetables'),
        (186, 'Kadhi Chawal',         'dinner', 480, 14, 65, 14, 65,  'veg',                  'dairy',     'yogurt,besan,rice'),
        (187, 'Egg Salad Bowl',       'dinner', 360, 24, 14, 18, 65,  'non-veg,high-protein,low-carb','',  'eggs,vegetables,lemon'),
        (188, 'Stuffed Paratha Curd', 'dinner', 540, 18, 65, 18, 70,  'veg',                  'gluten,dairy','wheat,vegetables,yogurt'),
        (189, 'Tomato Soup Bread',    'dinner', 360, 14, 45, 8,  55,  'veg,vegan',            'gluten',    'tomato,bread,spices'),
        (190, 'Mutton Keema Roti',    'dinner', 620, 38, 45, 30, 170, 'non-veg,high-protein', 'gluten',    'mutton,wheat,onion'),
        (191, 'Veg Clear Soup',       'dinner', 280, 8,  35, 6,  50,  'veg,vegan,gf,low-carb','',          'mixed-veg,broth,spices'),
        (192, 'Curd Rice',            'dinner', 420, 14, 60, 10, 50,  'veg',                  'dairy',     'rice,yogurt,spices'),
        (193, 'Tawa Chicken Roti',    'dinner', 520, 38, 38, 22, 145, 'non-veg,high-protein', 'gluten',    'chicken,wheat,onion'),
        (194, 'Tofu Stir Fry Rice',   'dinner', 480, 28, 45, 18, 100, 'veg,vegan,high-protein','soy',      'tofu,vegetables,rice'),
        (195, 'Veg Pulao',            'dinner', 460, 14, 65, 12, 65,  'veg,vegan,gf',         '',          'rice,vegetables,spices'),
        (196, 'Chicken Pulao',        'dinner', 580, 32, 60, 20, 140, 'non-veg,high-protein', '',          'rice,chicken,spices'),
        (197, 'Mutton Stew',          'dinner', 540, 36, 30, 26, 170, 'non-veg,high-protein,low-carb','',  'mutton,vegetables,broth'),
        (198, 'Veg Stew',             'dinner', 380, 12, 40, 16, 70,  'veg,vegan,gf,low-carb','',          'mixed-veg,coconut,spices'),
        (199, 'Tom Yum Soup',         'dinner', 320, 22, 30, 10, 100, 'non-veg,high-protein,low-carb','',  'shrimp,lemongrass,broth'),
        (200, 'Veg Manchurian Rice',  'dinner', 540, 14, 65, 18, 90,  'veg,vegan',            'gluten,soy','vegetables,rice,sauce'),
        (201, 'Chicken Manchurian Rice','dinner',620, 32, 60, 22, 140, 'non-veg,high-protein','gluten,soy','chicken,rice,sauce'),
        (202, 'Roti Sabzi Dal',       'dinner', 480, 18, 60, 14, 70,  'veg,vegan',            'gluten',    'wheat,mixed-veg,lentils'),
        (203, 'Roti Chicken Curry',   'dinner', 580, 36, 50, 22, 140, 'non-veg,high-protein', 'gluten',    'wheat,chicken,onion'),
        (204, 'Aloo Methi Roti',      'dinner', 480, 14, 55, 18, 60,  'veg,vegan',            'gluten',    'potato,fenugreek,wheat'),
        (205, 'Bharwa Bhindi Roti',   'dinner', 460, 12, 50, 18, 70,  'veg,vegan',            'gluten',    'okra,wheat,spices'),
        (206, 'Cabbage Sabzi Roti',   'dinner', 420, 12, 50, 14, 60,  'veg,vegan',            'gluten',    'cabbage,wheat,spices'),
        (207, 'Egg Tikka Masala',     'dinner', 480, 28, 30, 24, 90,  'non-veg,high-protein', '',          'eggs,onion,tomato'),
        (208, 'Tofu Tikka Masala',    'dinner', 460, 26, 30, 22, 100, 'veg,vegan,high-protein','soy',      'tofu,onion,tomato'),
        (209, 'Paneer Tikka Masala',  'dinner', 540, 28, 35, 28, 110, 'veg,high-protein',     'dairy',     'paneer,cream,tomato'),
        (210, 'Hyderabadi Chicken',   'dinner', 580, 38, 30, 28, 150, 'non-veg,high-protein', 'dairy,nuts','chicken,cream,nuts'),
        (211, 'Veg Korma',            'dinner', 480, 14, 50, 22, 90,  'veg',                  'dairy,nuts','mixed-veg,cream,nuts'),
        (212, 'Pumpkin Soup',         'dinner', 320, 10, 45, 8,  60,  'veg,gf,low-carb',      'dairy',     'pumpkin,milk,spices'),
        (213, 'Mushroom Soup',        'dinner', 280, 12, 30, 10, 70,  'veg,gf,low-carb',      'dairy',     'mushroom,milk,spices'),
        (214, 'Chicken Clear Soup',   'dinner', 280, 32, 12, 8,  120, 'non-veg,high-protein,low-carb','',  'chicken,broth,vegetables'),
        (215, 'Greek Salad Chicken',  'dinner', 380, 36, 18, 18, 140, 'non-veg,high-protein,low-carb','dairy','chicken,feta,vegetables'),
        (216, 'Greek Salad Veg',      'dinner', 320, 14, 22, 18, 100, 'veg,gf,low-carb',      'dairy',     'feta,vegetables,olives'),
        (217, 'Boiled Chicken Salad', 'dinner', 380, 42, 14, 16, 130, 'non-veg,high-protein,low-carb','',  'chicken,vegetables,lemon'),
        (218, 'Chickpea Salad',       'dinner', 380, 22, 40, 12, 70,  'veg,vegan,gf,high-protein','',      'chickpea,vegetables,lemon'),
        (219, 'Quinoa Salad',         'dinner', 420, 18, 50, 14, 90,  'veg,vegan,gf,high-protein','',      'quinoa,vegetables,lemon'),
        (220, 'Tuna Salad',           'dinner', 380, 38, 14, 18, 140, 'non-veg,high-protein,low-carb','',  'tuna,vegetables,mayo'),
        (221, 'Paneer Salad',         'dinner', 380, 24, 18, 22, 90,  'veg,gf,high-protein,low-carb','dairy','paneer,vegetables,lemon'),
        (222, 'Tofu Salad',           'dinner', 360, 22, 22, 18, 90,  'veg,vegan,gf,high-protein,low-carb','soy','tofu,vegetables,lemon'),
        (223, 'Chicken Wrap',         'dinner', 520, 32, 45, 22, 130, 'non-veg,high-protein', 'gluten',    'chicken,wheat,vegetables'),
        (224, 'Falafel Wrap',         'dinner', 480, 18, 55, 18, 90,  'veg,vegan',            'gluten',    'chickpea,wheat,vegetables'),
        (225, 'Veg Burger',           'dinner', 480, 14, 55, 22, 90,  'veg',                  'gluten,dairy','bun,patty,cheese'),
        (226, 'Chicken Burger',       'dinner', 540, 32, 50, 22, 130, 'non-veg,high-protein', 'gluten,dairy','bun,chicken,cheese'),
        (227, 'Egg Curry Rice',       'dinner', 540, 26, 60, 22, 80,  'non-veg,high-protein', '',          'eggs,rice,onion'),
        (228, 'Mushroom Stroganoff',  'dinner', 480, 16, 50, 22, 120, 'veg',                  'gluten,dairy','mushroom,pasta,cream'),
        (229, 'Chicken Stroganoff',   'dinner', 580, 36, 45, 26, 150, 'non-veg,high-protein', 'gluten,dairy','chicken,pasta,cream'),
        (230, 'Veg Lasagna',          'dinner', 540, 22, 55, 24, 130, 'veg',                  'gluten,dairy','pasta,vegetables,cheese'),
        (231, 'Chicken Lasagna',      'dinner', 620, 38, 50, 28, 160, 'non-veg,high-protein', 'gluten,dairy','pasta,chicken,cheese'),
        (232, 'Spinach Soup',         'dinner', 280, 12, 30, 10, 60,  'veg,gf,low-carb',      'dairy',     'spinach,milk,spices'),
        (233, 'Mixed Lentil Soup',    'dinner', 360, 22, 45, 8,  55,  'veg,vegan,gf,high-protein','',      'lentils,vegetables,spices'),
        (234, 'Sweet Corn Soup',      'dinner', 320, 10, 50, 6,  60,  'veg',                  'gluten',    'corn,vegetables,broth'),
        (235, 'Hot Sour Soup',        'dinner', 280, 14, 30, 10, 70,  'veg,vegan',            'soy',       'vegetables,tofu,broth'),
        (236, 'Roti Paneer Sabzi',    'dinner', 540, 26, 50, 22, 100, 'veg,high-protein',     'gluten,dairy','wheat,paneer,vegetables'),
        (237, 'Roti Chicken Sabzi',   'dinner', 580, 38, 45, 22, 140, 'non-veg,high-protein', 'gluten',    'wheat,chicken,vegetables'),
        (238, 'Methi Mushroom Roti',  'dinner', 460, 14, 50, 18, 70,  'veg,vegan',            'gluten',    'mushroom,fenugreek,wheat'),
        (239, 'Egg Curry Roti',       'dinner', 520, 26, 50, 22, 80,  'non-veg,high-protein', 'gluten',    'eggs,wheat,onion'),
        (240, 'Bhindi Sabzi Roti',    'dinner', 440, 12, 50, 16, 65,  'veg,vegan',            'gluten',    'okra,wheat,spices'),

        # ───────────── SNACKS (241-310) ─────────────
        (241, 'Roasted Chana',         'snack', 180, 12, 22, 4,  20,  'veg,vegan,gf,high-protein','',      'chickpeas,spices'),
        (242, 'Boiled Eggs (2)',       'snack', 160, 14, 2,  10, 30,  'non-veg,keto,high-protein','',      'eggs,salt'),
        (243, 'Greek Yogurt Cup',      'snack', 180, 16, 14, 6,  60,  'veg,high-protein',         'dairy', 'yogurt,honey'),
        (244, 'Peanut Chikki',         'snack', 220, 10, 25, 12, 25,  'veg,vegan,gf',             'nuts',  'peanuts,jaggery'),
        (245, 'Banana Peanut Butter',  'snack', 280, 10, 32, 14, 40,  'veg,vegan,gf,high-protein','nuts',  'banana,peanut-butter'),
        (246, 'Paneer Cubes',          'snack', 220, 22, 4,  14, 70,  'veg,keto,high-protein',    'dairy', 'paneer,spices'),
        (247, 'Mixed Nuts',            'snack', 220, 8,  12, 18, 60,  'veg,vegan,gf,keto',        'nuts',  'almonds,cashews,walnuts'),
        (248, 'Apple + Almonds',       'snack', 220, 8,  28, 10, 50,  'veg,vegan,gf,high-protein','nuts',  'apple,almonds'),
        (249, 'Sprouts Bhel',          'snack', 220, 14, 30, 4,  30,  'veg,vegan,gf,high-protein','',      'sprouts,onion,lemon'),
        (250, 'Hummus + Carrot',       'snack', 240, 12, 22, 12, 70,  'veg,vegan,gf,high-protein','',      'chickpeas,tahini,carrot'),
        (251, 'Protein Shake',         'snack', 280, 32, 14, 6,  100, 'veg,high-protein',         'dairy', 'whey,milk,banana'),
        (252, 'Bhel Puri',             'snack', 220, 8,  35, 5,  30,  'veg,vegan',                'gluten','puffed-rice,onion,chutney'),
        (253, 'Dhokla (3 pcs)',        'snack', 220, 12, 32, 6,  40,  'veg,gf,high-protein',      '',      'besan,yogurt,spices'),
        (254, 'Boiled Chana Chaat',    'snack', 240, 16, 32, 4,  35,  'veg,vegan,gf,high-protein','',      'chickpeas,onion,lemon'),
        (255, 'Cheese Crackers',       'snack', 240, 12, 20, 14, 60,  'veg,high-protein',         'dairy,gluten','cheese,crackers'),
        (256, 'Chicken Sandwich',      'snack', 320, 26, 28, 12, 80,  'non-veg,high-protein',     'gluten','chicken,bread,mayo'),
        (257, 'Fruit Salad',           'snack', 200, 4,  45, 2,  50,  'veg,vegan,gf',             '',      'mixed-fruits,honey'),
        (258, 'Masala Peanuts',        'snack', 250, 12, 14, 18, 30,  'veg,vegan,gf,high-protein','nuts',  'peanuts,spices'),
        (259, 'Idli (2 pcs)',          'snack', 160, 5,  32, 1,  25,  'veg,vegan,gf',             '',      'rice,urad-dal'),
        (260, 'Egg Salad Cup',         'snack', 220, 18, 4,  14, 40,  'non-veg,keto,high-protein','',      'eggs,vegetables,mayo'),
        (261, 'Cottage Cheese Bowl',   'snack', 220, 24, 6,  12, 80,  'veg,keto,high-protein,low-carb','dairy','paneer,vegetables'),
        (262, 'Tofu Cubes',            'snack', 200, 22, 6,  12, 70,  'veg,vegan,keto,high-protein','soy','tofu,spices'),
        (263, 'Almond Milk Smoothie',  'snack', 260, 10, 35, 10, 90,  'veg,vegan,gf',             'nuts',  'almond-milk,banana,oats'),
        (264, 'Whey Smoothie',         'snack', 320, 32, 30, 6,  100, 'veg,high-protein',         'dairy', 'whey,milk,fruits'),
        (265, 'Chicken Skewers',       'snack', 280, 32, 8,  14, 100, 'non-veg,high-protein,low-carb','',  'chicken,vegetables,spices'),
        (266, 'Paneer Skewers',        'snack', 260, 22, 10, 16, 80,  'veg,high-protein,low-carb','dairy', 'paneer,vegetables,spices'),
        (267, 'Tofu Skewers',          'snack', 240, 22, 10, 14, 80,  'veg,vegan,high-protein,low-carb','soy','tofu,vegetables,spices'),
        (268, 'Veg Cutlet',            'snack', 220, 8,  28, 10, 35,  'veg,vegan',                '',      'potato,vegetables,spices'),
        (269, 'Chicken Cutlet',        'snack', 280, 24, 18, 14, 80,  'non-veg,high-protein',     '',      'chicken,potato,spices'),
        (270, 'Egg Bhurji Cup',        'snack', 220, 18, 6,  14, 40,  'non-veg,keto,high-protein','',      'eggs,onion,spices'),
        (271, 'Fruit Yogurt',          'snack', 200, 14, 28, 4,  60,  'veg,gf,high-protein',      'dairy', 'yogurt,fruits'),
        (272, 'Banana Shake',          'snack', 260, 12, 38, 8,  60,  'veg,gf,high-protein',      'dairy', 'banana,milk,sugar'),
        (273, 'Mango Shake',           'snack', 280, 10, 45, 6,  70,  'veg,gf',                   'dairy', 'mango,milk,sugar'),
        (274, 'Chocolate Smoothie',    'snack', 300, 14, 40, 8,  80,  'veg,gf,high-protein',      'dairy', 'chocolate,milk,banana'),
        (275, 'Chia Pudding',          'snack', 240, 10, 30, 10, 70,  'veg,vegan,gf,high-protein','',      'chia-seeds,milk,fruits'),
        (276, 'Granola Bowl',          'snack', 280, 10, 40, 10, 80,  'veg',                      'gluten,nuts,dairy','granola,milk,fruits'),
        (277, 'Egg Frittata',          'snack', 240, 22, 6,  16, 60,  'non-veg,keto,high-protein','dairy', 'eggs,cheese,vegetables'),
        (278, 'Chicken Tikka Cup',     'snack', 260, 28, 8,  14, 100, 'non-veg,high-protein,low-carb','',  'chicken,yogurt,spices'),
        (279, 'Paneer Tikka Cup',      'snack', 240, 20, 10, 14, 80,  'veg,high-protein,low-carb','dairy', 'paneer,yogurt,spices'),
        (280, 'Quinoa Salad Cup',      'snack', 240, 12, 32, 8,  70,  'veg,vegan,gf,high-protein','',      'quinoa,vegetables,lemon'),
        (281, 'Veg Sandwich',          'snack', 260, 8,  32, 10, 50,  'veg',                      'gluten,dairy','bread,vegetables,cheese'),
        (282, 'Tuna Sandwich',         'snack', 320, 26, 28, 12, 100, 'non-veg,high-protein',     'gluten','tuna,bread,mayo'),
        (283, 'Egg Sandwich Snack',    'snack', 280, 18, 26, 12, 50,  'non-veg,high-protein',     'gluten','eggs,bread,mayo'),
        (284, 'Hung Curd Bowl',        'snack', 200, 16, 12, 10, 60,  'veg,gf,high-protein',      'dairy', 'yogurt,spices'),
        (285, 'Beetroot Tikki',        'snack', 200, 6,  28, 8,  35,  'veg,vegan',                '',      'beetroot,potato,spices'),
        (286, 'Soya Cutlet',           'snack', 240, 18, 22, 10, 50,  'veg,high-protein',         'soy',   'soya,potato,spices'),
        (287, 'Mixed Sprouts',         'snack', 200, 16, 26, 4,  35,  'veg,vegan,gf,high-protein','',      'sprouts,onion,lemon'),
        (288, 'Roasted Makhana',       'snack', 180, 6,  28, 6,  40,  'veg,vegan,gf',             '',      'makhana,ghee,spices'),
        (289, 'Trail Mix',             'snack', 240, 8,  22, 16, 70,  'veg,vegan,gf',             'nuts',  'nuts,seeds,raisins'),
        (290, 'Roasted Almonds',       'snack', 200, 8,  6,  18, 80,  'veg,vegan,gf,keto',        'nuts',  'almonds,salt'),
        (291, 'Peanut Butter Toast',   'snack', 280, 12, 30, 14, 50,  'veg,vegan,high-protein',   'gluten,nuts','bread,peanut-butter'),
        (292, 'Cheese Toast',          'snack', 280, 14, 28, 14, 60,  'veg,high-protein',         'gluten,dairy','bread,cheese'),
        (293, 'Veg Roll',              'snack', 280, 10, 32, 12, 50,  'veg,vegan',                'gluten','wheat,vegetables,spices'),
        (294, 'Paneer Roll',           'snack', 320, 18, 30, 14, 70,  'veg,high-protein',         'gluten,dairy','paneer,wheat,vegetables'),
        (295, 'Chicken Roll Snack',    'snack', 340, 24, 28, 14, 90,  'non-veg,high-protein',     'gluten','chicken,wheat,vegetables'),
        (296, 'Egg Roll',              'snack', 320, 18, 30, 14, 60,  'non-veg,high-protein',     'gluten','eggs,wheat,vegetables'),
        (297, 'Boiled Corn',           'snack', 180, 6,  35, 4,  30,  'veg,vegan,gf',             '',      'corn,butter,spices'),
        (298, 'Steamed Sprouts',       'snack', 180, 14, 25, 2,  30,  'veg,vegan,gf,high-protein','',      'sprouts,lemon,salt'),
        (299, 'Edamame',               'snack', 200, 18, 16, 8,  100, 'veg,vegan,gf,high-protein','soy',   'edamame,salt'),
        (300, 'Smoked Tofu',           'snack', 220, 22, 6,  12, 90,  'veg,vegan,gf,high-protein,keto','soy','tofu,spices'),
        (301, 'Baked Sweet Potato',    'snack', 200, 4,  44, 2,  35,  'veg,vegan,gf',             '',      'sweet-potato,spices'),
        (302, 'Veg Pakora',            'snack', 240, 8,  28, 12, 35,  'veg,vegan',                '',      'besan,vegetables,spices'),
        (303, 'Onion Pakora',          'snack', 220, 6,  28, 10, 30,  'veg,vegan',                '',      'besan,onion,spices'),
        (304, 'Paneer Pakora',         'snack', 280, 18, 18, 16, 70,  'veg,high-protein',         'dairy', 'paneer,besan,spices'),
        (305, 'Chicken Nuggets',       'snack', 320, 24, 22, 14, 110, 'non-veg,high-protein',     'gluten','chicken,bread-crumbs'),
        (306, 'Fish Fingers',          'snack', 300, 26, 20, 14, 130, 'non-veg,high-protein',     'gluten','fish,bread-crumbs'),
        (307, 'Veg Spring Roll',       'snack', 240, 8,  32, 10, 50,  'veg,vegan',                'gluten','flour,vegetables'),
        (308, 'Chicken Spring Roll',   'snack', 280, 18, 28, 12, 80,  'non-veg,high-protein',     'gluten','chicken,flour,vegetables'),
        (309, 'Banana Smoothie Bowl',  'snack', 280, 10, 42, 8,  70,  'veg',                      'dairy', 'banana,yogurt,oats'),
        (310, 'Berry Smoothie',        'snack', 240, 8,  35, 6,  90,  'veg,gf',                   'dairy', 'berries,yogurt'),
    ]

    c.executemany(
        'INSERT OR IGNORE INTO recipes VALUES (?,?,?,?,?,?,?,?,?,?,?)',
        recipes
    )
    conn.commit()
    conn.close()
    print(f"Database ready with {len(recipes)} recipes.")

if __name__ == "__main__":
    init_db()